name: RestAPI-CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    needs: maven-check
    
    steps:
      - name: clone this Repo
        uses: actions/checkout@v1
      
      - name: run all tests
        run: mvn test

  maven-check:
    runs-on: ubuntu-latest
    
    needs: allure-check
    
    steps:
      - name: Maven check
        run: mvn -version
  
  allure-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Allure check
        run: allure --version
